kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: instance-developers
  namespace: instance-developers
  uid: c5babfe3-8d6b-4ec2-9c0b-c7cbccaad305
  resourceVersion: '211796'
  creationTimestamp: '2024-08-01T06:49:48Z'
  managedFields:
    - manager: Mozilla
      operation: Update
      apiVersion: rbac.authorization.k8s.io/v1
      time: '2024-08-01T06:49:48Z'
      fieldsType: FieldsV1
      fieldsV1:
        'f:roleRef': {}
        'f:subjects': {}
subjects:
  - kind: Group
    apiGroup: rbac.authorization.k8s.io
    name: developers
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: admin
